### ISSUE TITLE
All colors in all themes are black since latest tinted-theming-bot commit

### ISSUE THREAD

**Issue by didoesdigital** [tinted-theming/tinted-iterm2#10]
It looks like [this commit](https://github.com/tinted-theming/base16-iterm2/commit/5646dc8a290eed1df356e4da6d34fcfc29dfb32b) changed 798 colorschemes and set all their color values to 0, producing black-only colorschemes.

For anyone that wants to use the previous colorschemes, you can [browse files at the last good commit](https://github.com/tinted-theming/base16-iterm2/tree/1040b06568575def89b78ba7ce83a117b20745c2)

**Comment by JamyGolden** [comment]
Thanks for creating the issue, there was a bug fixed in the builder which should prevent this from happening again https://github.com/tinted-theming/tinted-builder-rust/pull/5
