### ISSUE TITLE
Feature: Use semantic colors instead of making assumptions about hues

### ISSUE THREAD

**Issue by joshgoebel** [tinted-theming/tinted-iterm2#5]
Ref:
- https://github.com/base16-project/base16/issues/10
- https://github.com/base16-project/base16/issues/11

Should prefer semantic `term01` colors (or some other solution)  rather than assuming hues... ie, we should not assume that `base08` is RED.  To have anything resembling a "normal" terminal palette (which some may desire) right now one is forced to use specific hues for `base08`-`base0F`, this should not be required.

Also the current mapping seems pretty arbitrary given that the style spec says nothing at all (that I can see) about guaranteed hues - I assume we're getting this current mapping only from the default Base16 theme...

**Alternatives considered**

Different schemes per template (to allow mapping colors differently per template):

- nord-terminal-scheme
- nord-vscode-scheme

But doesn't that kind of defeat the purpose?

**Comment by JamyGolden** [comment]
I'm going to close this since our [styling spec](https://github.com/tinted-theming/home/blob/main/styling.md) now encourages people to put certain colors in specific base0x mapping spots.
